### PR TITLE
Store

### LINKED ISSUE #20: Solve crashing for csv click
When clicking on a location in the ListViewCustom page causes the app to crash and return to the main activity page.

### PR DESCRIPTION
**Pull request by NathanHenrySchneider**
- Stores and their items are now persisted on a central model
- Moved CSV read-in to happen when the welcome screen is opened
- Store detail view hides "Add item" button for regular users
- After adding a new item for donation, the list of store items refreshes to show the new item

Missing items:

- [ ] We still don't have the short and long description fields
- [ ] The item detail view is ugly (#26)
- [ ] We should probably use more "Record donation" terminology instead of "item" (#25) 

Closes #20

### CODE REVIEW

File: app/src/main/java/com/scrumbums/donationboi/model/util/AccountValidation.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ public static final boolean isValidEmail(String s) {
      */
     public static final boolean isValidPassword(String s) {
         return isStringNonEmpty(s) && !containsIllegalCharacters(s)
-                && s.length() >= MINPASSWORDLENGTH && hasMinChars(s);
```
Comment (gibrane) [inline app/src/main/java/com/scrumbums/donationboi/model/util/AccountValidation.java]: probably should revert this
